### ISSUE TITLE
How to update from a dowloaded DB

### ISSUE THREAD

**Issue by davidnovotech** [mathieulavoie/Bitcluster#11]
Hi,

I am not too sure about the procedure to update the database after it has been build from the one available through torrent download.

What I tried to do : 
- Get last block from mongo using this command 
  db.transactions.find({}).sort({_id:-1}).limit(1);
  { "_id" : ObjectId("57c834d8e65b9d53a69b7dc1"), "amount" : 0.33435414, "amount_usd" : 225.30219676002, "destination_n_id" : 18722861, "**block_id" : 421422**, "trx_date" : "2016-07-19", "destination" : "12BQGj7T7aWdDBpKNbhKDyTm46ZdWc4kBC", "source_n_id" : 58723676, "source" : "1PzMToMuk2h5DnNKNekMBL59af1a1oWghW" }
- Build DB
  $ python build_cluster.py  421422
  (Takes forever to sync when the script says waiting  but mongo shows activities in logs)
- Map DB
  $ python map_money.py 421422 427822 (Where the build "stoped")

*This step is failing  with an http error  BadStatusLine

Can you please tell how I should proceed to update ? 

Is there a way to update using the DB available through torrent ? Is it up to date ?

**Comment by mathieulavoie** [comment]
Both command are good : it is the actual way to update an existing database. 
- Build DB
  On my setup (SSD, 64GB RAM and i7) it take approximately 1 hours to add a batch of 2500 blocks to the database. I would not recommend to keep mongoDB files on an HDD. The disk IO is probably the most crucial part for the clustering and the mapping.
- Map DB
  The USD/BTC conversion table is downloaded over HTTP from CoinDesk when the MoneyCrawler is initialized.  This seem to be the source of your issue. I'm not able to reproduce. Make sure that the machine on which you run the script can reach _https://api.coindesk.com_. See lines 19 to 21 of money_crawler.py.

I'm finishing updating the database today. If everything goes as expected, a new version of the database (up to 427700) should be available by torrent during the weekend (September 3-4).

**Comment by mathieulavoie** [comment]
New version of the database is available on https://www.bit-cluster.com. It goes to September 2nd /block 428000.

**Comment by davidnovotech** [comment]
Thank you,

I will try this or else re-download the DB.
