### ISSUE TITLE
Database download impossible

### ISSUE THREAD

**Issue by benediktjordan** [mathieulavoie/Bitcluster#18]
Hi, 

Is this project still active? 
The page http://dev.bit-cluster.com/magnet for downloading the database is not working (for me). Error message: ERR_CONNECTION_REFUSED comes up. 

Does anybody knows what to do? 

Thanks a lot!

**Comment by mathieulavoie** [comment]
Link is now up.

The project is still active, but I didn't have much time lately for this project. 

Thanks

**Comment by maxtwen** [comment]
The page http://dev.bit-cluster.com/magnet for downloading the database is not working again
